apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-webhook
    developer: devang
  name: k8s-webhook
  namespace: dg-webhook
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8443
  selector:
    app: k8s-webhook
  type: ClusterIP
